#!/bin/bash 

set -e

cd $(dirname $0)/..


. ./scripts/common_functions
set_project_vars

GITCOMMIT=`git rev-parse --short HEAD`

if [ -L ${PACKAGE} ]; then
    rm ${PACKAGE}
fi

if [ ! -e ${PACKAGE} ]; then
    mkdir -p $(dirname $PACKAGE)
    ln -s $(pwd) $PACKAGE
fi

rm -rf build
mkdir -p build
go build -o build/${PROJECT} -ldflags "-X main.GITCOMMIT $GITCOMMIT"
