#!/bin/bash 

set -e

cd $(dirname $0)/..


. ./scripts/common_functions
set_project_vars

GITCOMMIT=`git rev-parse --short HEAD`

rm -rf build
mkdir -p build
go build -o build/${PROJECT} -a -tags "netgo" -installsuffix netgo -ldflags "-linkmode external -extldflags -static -X main.GITCOMMIT=$GITCOMMIT"
